### ISSUE TITLE
看上去不错

### ISSUE THREAD

**Issue by Hello-XPH** [mgsweet/FreeRSS#21]
有安装包吗

**Comment by mgsweet** [comment]
暂时没有安装包哈，大二写的代码，做完后一直废置，应该还有不少bug。接受pull request哈～

**Comment by Hello-XPH** [comment]
难受了，大佬有时间弄一下。哈哈哈哈

**Comment by jianjieluo** [comment]
感谢你的关注！

由于本项目完成于2017年，至今 windows10 的版本已经迭代多个大版本。当初开发使用的 SDK 版本、Visual Stuio 版本、相关依赖库版本、信任证书机制、微软对UWP的支持力度等与现在相比相差太大，导致开发成本骤增，因此近期可能无法提供相应的安装包，抱歉。

你可以尝试自己在 visual studio 下编译运行，再次感谢你的关注！
